name: ✅ Test Build Library

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "v1/src/**"
      - "v1/linker_scripts/**"
      - "v1/include/**"
      - "v1/tests/**"
      - "v1/test_package/**"
  push:
    paths:
      - "v1/src/**"
      - "v1/linker_scripts/**"
      - "v1/include/**"
      - "v1/tests/**"
      - "v1/test_package/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@5.x.y
    with:
      dir: v1
    secrets: inherit

  deploy_gcc:
    uses: ./.github/workflows/deploy_with_cache.yml
    with:
      compiler_profile: hal/tc/arm-gcc
      version: latest
      upload_suffix: gcc
      library_dir: v1
    secrets: inherit

  deploy_llvm:
    uses: ./.github/workflows/deploy_with_cache.yml
    with:
      compiler_profile: hal/tc/llvm
      version: latest
      upload_suffix: llvm
      library_dir: v1
    secrets: inherit
